name: Build and Push

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: neural-diwan-435305
  GKE_CLUSTER: astro-blog-cluster
  GKE_ZONE: us-central1-a

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}

    - name: Verify Google Cloud authentication
      run: |
        gcloud auth list
        gcloud config list
        gcloud projects list
        gcloud container images list

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build Docker image
      run: docker build . -t gcr.io/${{ env.PROJECT_ID }}/astro-blog:${{ github.sha }}

    - name: Push Docker image
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://gcr.io
        docker push gcr.io/${{ env.PROJECT_ID }}/astro-blog:${{ github.sha }}

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }}

    - name: Deploy to GKE
      run: kubectl set image deployment/astro-blog astro-blog=gcr.io/${{ env.PROJECT_ID }}/astro-blog:${{ github.sha }}